changelog:
  categories:
    - title: "⚠️ Breaking Changes"
      labels:
        - breaking
    - title: New Sources
      labels:
        - new-source
    - title: New Resources
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - new-source
          - enhancement
          - breaking
          - bug
          - documentation
